### ISSUE TITLE
pass eslint context on to plugins

### ISSUE THREAD

**Issue by patroza** [mmkal/eslint-plugin-codegen#16]
https://github.com/effect-ts-app/libs/blob/main/patches/eslint-plugin-codegen%400.17.0.patch

**Comment by mmkal** [comment]
This looks useful, yes, although could you share more about what your usecase is? I don't want to "gatekeep" usefulness here - I use the `custom` preset more and more, and usually I just want to "full power" - that was why I added `glob`, `fs` and `path` to the `meta` object in https://github.com/mmkal/eslint-plugin-codegen/pull/14.

---

using this issue as a sounding board...

Having said that, I don't think they actually belong on `meta`, since they're not metadata. Probably they should be top-level properties. In general I prefer single-arg functions in javascript, using an "options bag", unless the ordering is obvious and meaningful like `const subtract = (a, b) => a - b` or whatever.

So what about just passing the context directly, along with whatever else makes sense on the top level:

```js
return preset({
  options: opts,
  context,
  existingContent,
  glob,
  fs,
  path,
  lodash,
  jsYaml,
  // ...other dependencies which might be useful at lint-time, but likely won't be wanted as production dependencies for end users
})
```

Usage:

```js
export const generateStuff: import('eslint-plugin-codegen').Preset<{}> = ({ context, glob, lodash, path }) => {
  const filename = context.getFilename()
  const files = glob.globSync('**/*.foo.ts', {  cwd: path.dirname(filename) })
  return `const children = JSON.stringify(lodash.uniqBy(files, f => f.split('.')[0]))
}

// codegen:start {preset: custom, export: generateStuff}
const children = ["one.foo.ts", "two.foo.ts"]
// codegen: end
```

**Comment by patroza** [comment]
> This looks useful, yes, although could you share more about what your usecase is? I don't want to "gatekeep" usefulness here - I use the `custom` preset more and more, and usually I just want to "full power" - that was why I added `glob`, `fs` and `path` to the `meta` object in #14.

thanks, my use case is retrieving the typescript compiler from the context and using it with the codegen plugins
https://github.com/effect-ts-app/libs/blob/main/packages/eslint-codegen-model/src/presets/model.ts#L56
