### ISSUE TITLE
Support generating from jsdoc classes

### ISSUE THREAD

**Issue by wSedlacek** [mmkal/eslint-plugin-codegen#8]
https://github.com/mmkal/ts/blob/43cf60beb6d0ed7efa349e9c1fe3770d0d9df0e8/packages/eslint-plugin-codegen/src/presets/markdown-from-jsdoc.ts#L25

This is only looking at variables and arrow functions, it would be cool if it could look for classes, abstract classes, interfaces, etc.

**Comment by mmkal** [comment]
Agreed, that would be nice. It doesn't exist now because I personally don't use classes much so didn't have a use case when this was first written. And parsing classes is much harder. Possibly there is a library that could be used to pull out all the comments. A PR would be welcome but it could be a lot of work! In the meantime you may want to look at a more heavyweight tool like https://api-extractor.com/

**Comment by mmkal** [comment]
@wSedlacek released in v0.27.0. I hope you haven't been waiting for the last 2.5 years!

**Comment by wSedlacek** [comment]
I have been busy working on rebuilding the entire networking layer for our product with gRPC and microservices 😄 
Thank you for getting this fixed!
